"use strict";
import formValidation from "./modules/contactForm.mjs";
import navigationScript from "./modules/navigation.mjs";
import productsScript from "./modules/products.mjs";
import registerFormScript from "./modules/registerForm.mjs";
import spanAppendScript from "./modules/spanAppend.mjs";
formValidation();
navigationScript();
productsScript();
registerFormScript();
spanAppendScript();
